### PR TITLE
Pull request (issues_jh -> develop)

### PR DESCRIPTION
**Pull request by herjmoo**
Add throw exception capability through API calls

### CODE REVIEW

**Comment by chuckyount** [comment]
I got the following error when trying to run "make -j all"
...
make[4]: Leaving directory `/nfs/pdx/home/cyount/dev/github/yask-develop.clean/src/kernel'
make[3]: Leaving directory `/nfs/pdx/home/cyount/dev/github/yask-develop.clean'
make stencil=test py-yc-api-and-py-yk-api-test-with-exception
make[3]: Entering directory `/nfs/pdx/home/cyount/dev/github/yask-develop.clean'
make -C src/kernel py-yc-api-test-with-exception
make[4]: Entering directory `/nfs/pdx/home/cyount/dev/github/yask-develop.clean/src/kernel'
make -C ../compiler py-yc-api-test-with-exception
make[5]: Entering directory `/nfs/pdx/home/cyount/dev/github/yask-develop.clean/src/compiler'
make[5]: *** No rule to make target `/nfs/pdx/home/cyount/dev/github/yask-develop.clean/bin/yask_compiler_api_exception_test.py', needed by `py-yc-api-test-with-exception'.  Stop.
make[5]: Leaving directory `/nfs/pdx/home/cyount/dev/github/yask-develop.clean/src/compiler'
make[4]: *** [py-yc-api-test-with-exception] Error 2
make[4]: Leaving directory `/nfs/pdx/home/cyount/dev/github/yask-develop.clean/src/kernel'
make[3]: *** [py-yc-api-and-py-yk-api-test-with-exception] Error 2
make[3]: Leaving directory `/nfs/pdx/home/cyount/dev/github/yask-develop.clean'
make[2]: *** [api-tests] Error 2
make[2]: Leaving directory `/nfs/pdx/home/cyount/dev/github/yask-develop.clean'
make[1]: *** [all-tests] Error 2
make[1]: Leaving directory `/nfs/pdx/home/cyount/dev/github/yask-develop.clean'
make: *** [all] Error 2

Maybe a file is missing?

**Comment by chuckyount** [comment]
Now I'm getting this error. I wonder if it's a difference between python 2 and 3?

make stencil=test py-yc-api-and-py-yk-api-test-with-exception
make[3]: Entering directory `/nfs/pdx/home/cyount/dev/github/yask-develop.clean'
make -C src/kernel py-yc-api-test-with-exception
make[4]: Entering directory `/nfs/pdx/home/cyount/dev/github/yask-develop.clean/src/kernel'
make -C ../compiler py-yc-api-test-with-exception
make[5]: Entering directory `/nfs/pdx/home/cyount/dev/github/yask-develop.clean/src/compiler'
chmod 440 yc-api-test-with-exception-py-readonly
*** Running the Python YASK compiler API test with exception...
env PYTHONPATH=/nfs/pdx/home/cyount/dev/github/yask-develop.clean/lib:/nfs/pdx/home/cyount/dev/github/yask-develop.clean/yask python /nfs/pdx/home/cyount/dev/github/yask-develop.clean/bin/yask_compiler_api_exception_test.py
  File "/nfs/pdx/home/cyount/dev/github/yask-develop.clean/bin/yask_compiler_api_exception_test.py", line 63
    except yask_compiler.yask_exception, e:
                                       ^
SyntaxError: invalid syntax

**Comment by chuckyount** [comment]
Looking much better! All Devito tests now pass!
In src/kernel/lib/settings.cpp, can the last exception use the macro?

**Comment by chuckyount** [comment]
THROW_YASK_EXCEPTION macro definition probably shouldn't be in the public API file. How about creating src/common/common_utils.hpp and put it there?

**Comment by chuckyount** [comment]
Also, let's make this version 2.02.00 since it's a pretty big change.

**Comment by herjmoo** [comment]
Done!

**Comment by chuckyount** [comment]
Closes #56.

**Pull request closed without merging**
